### PR TITLE
add true namespacing and remove custom "autoloading"

### PR DESCRIPTION
**Pull request by th3fallen**
i have very little hope that this will be merged since most places loath large pr's like this but since you sing about 100% code coverage maybe you guys can be different. 

You'll notice all tests pass except integration tests as i cant test those locally and im sure they are missing some updated `imports` etc

Hope this helps :)

### CODE REVIEW

**Comment by th3fallen** [comment]
whoops missed an import or two i see. will address please dont review yet.

**Comment by matthewpatterson** [comment]
Hey @th3fallen, we are in the process of looking over this pull request. It's going to take a little bit; as you can probably imagine, we have to do a thorough review of any changes we pull in. Thanks for the hard work!

**Comment by matthewpatterson** [comment]
Hey @th3fallen, sorry for the delay. I've been looking through this, but there seem to be a lot of things blocking the running of tests. I'm going to try to make inline comments where I can, but here are some patterns I have noticed:

- `use function` syntax - This was added in PHP 5.6, but our library supports (and builds against) PHP >= 5.4.
- Class names inside of strings - As far as I know, these must always be fully-qualified class names. Admittedly, I have not played with this on PHP 5.6, so it's possible that newer versions of the interpreter handle these more intelligently. But at least for me, they are causing class not found errors.
- Changes to relative file paths - We run tests from the root of the directory, and many places rely on relative file paths that are changed in this PR.

If it helps, I'm using PHP 5.4.4 and PHPUnit 3.7.38.

**Comment by th3fallen** [comment]
Hey @matthewpatterson sorry about that i overlooked what version of php you supported (noob mistake)

Thanks for taking the time to review, I've corrected the use function issue is this latest push.

The exception issues in your integration folder is due to me not being able to run those tests since they depend on some internal constraints on your side from what i saw? (clearly the only solution is to hire me so i can fix it :stuck_out_tongue_winking_eye: )

**Comment by crookedneighbor** [comment]
We've added support for PSR-4 namespacing in [version 3.6.0](https://github.com/braintree/braintree_php/releases/tag/3.6.0)  using an alternate method. Thanks for your work on this, it pushed us to implement it sooner.

Going to close this now since it's no longer needed.

**Comment by th3fallen** [comment]
@crookedneighbor Thanks for the update. Glad i could help.

**Pull request closed without merging**
