### PR TITLE
Update ClientToken.php

### PR DESCRIPTION
**Pull request by ovaisrafiqcs**
Factory method added in ClientToken.php

### CODE REVIEW

**Comment by matthewpatterson** [comment]
Hey @ovaisrafiqcs, `Braintree_ClientToken` is actually just a static class; it has no properties of its own and is never meant to be constructed, so I'm not sure why a factory method would be necessary.

**Comment by ovaisrafiqcs** [comment]
Hi @matthewpatterson 
When It comes to Symfony 2 framework, when I try to Generate Token it says as undefined service because this class have not defined any factory method because all other classes have and they are working if we call using factory so that’s why I added and requested the pull repository.It works in simple PHP but many PHP frameworks it will not work if we are using factory methods.

If this method will get added It will help me and other peoples as well for generating token.

**Comment by matthewpatterson** [comment]
@ovaisrafiqcs are you trying to register `Braintree_ClientToken` itself as a service in Symfony 2?

**Comment by ovaisrafiqcs** [comment]
@matthewpatterson no I am trying to call this service, I am using a third party bundle which uses php_braintree and I am trying to call clienttoken 

$factory = $this->get('comet_cult_braintree.factory');
$customerService = $factory->get('clienttoken');

If I call   $customerService = $factory->get('transaction'); or 
 $customerService = $factory->get('creditcard');
then It works but It doesnt work when I try to call "clienttoken"

**Comment by matthewpatterson** [comment]
@ovaisrafiqcs I see. It seems like `CometCultBraintreeBundle` is pretty much a wrapper for initializing `Braintree_` objects that act as services. However, `Braintree_ClientToken` isn't meant to be initialized in this way. Said another way, there is no use case for calling `new Braintree_ClientToken()` or `Braintree_ClientToken::factory()`.  Instead, you should use the following methods statically, for example `Braintree_ClientToken::generate($params);`.

**Comment by ovaisrafiqcs** [comment]
@matthewpatterson Its working by this way

not using CometCultBraintreeBundle and installed only braintree using composer

"braintree/braintree_php": "dev-master"

use Braintree_Configuration;
use Braintree_ClientToken;

Braintree_Configuration::environment('sandbox');
Braintree_Configuration::merchantId('merchantid');
Braintree_Configuration::publicKey('publickey');
Braintree_Configuration::privateKey('privatekey');

$clientToken = Braintree_ClientToken::generate();

Thanks

**Pull request closed without merging**
